name: Run Jest

on: pull_request

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🔑 Generate and use SSH key pair
        run: |
          mkdir ~/.ssh
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
          cat ~/.ssh/id_rsa.pub
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: 🤖 Install robotjs dependencies
        run: |
          sudo apt update
          sudo apt-get install libxtst-dev libpng++-dev

      - name: 📦 Install dependencies
        run: yarn

      - name: 🎭 Run Jest
        run: yarn test
