name: Check ESLint

on: pull_request

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: Install robotjs dependencies
        run: |
          sudo apt update
          sudo apt-get install libxtst-dev libpng++-dev

      - name: 📦 Install dependencies
        run: yarn

      - name: 🤓 Run ESLint
        run: yarn lint
