name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: yarn install
      - name: Publish package on NPM 📦
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package on NPM alias 📦
        run: yarn release:alias
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
