# publish as "react-native-ci-cli" instead of "setup-ci" for testing purposes

name: Publish to NPM with alias
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🍀 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: 📦 Install dependencies
        run: yarn

      - name: 🛠️ Build for alias
        run: yarn build:alias

      - name: 🚀 Publish package to NPM repository for alias
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
